### ISSUE TITLE
Can you add TLS1.3 support?

### ISSUE THREAD

**Issue by rdoorn** [schubergphilis/mercury#16]
Can you add TLS1.3 support to mercury?

**Comment by rdoorn** [comment]
TLS1.3 is currently planned for the golang version 1.11 milestone.

https://github.com/golang/go/issues/9671

Once the new golang with TLS1.3 is available we'll investigate if we need any additional coding to support this.

**Comment by adamkrellenstein** [comment]
Will this feature be included in golang 1.11 or 1.12 (as https://github.com/golang/go/issues/9671 says)?

**Comment by rdoorn** [comment]
Once the golang developers add support for TLS1.3 in the crypto libraries, Mercury will also support this.
The golang time-line at the time of writing suggests that this might be added in 1.11 or 1.12, but since the target seems to be moving, it will probably golang 1.12. the Draft for TLS1.3 got passed though, so i hope it won't be much longer...

**Comment by rdoorn** [comment]
implemented in de6f131, will be enabled by default in go1.13
